# Generated by Django 3.2.9 on 2022-11-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Blog_number',
            field=models.IntegerField(default=1),
        ),
    ]
